
services:

  wg-easy:
    image: weejewel/wg-easy:7
    container_name: wg-easy        
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PASSWORD=p4ssw0rd
      - WG_DEFAULT_DNS=1.1.1.1
      - WG_HOST=dominio.com   # IP
      - WG_PORT=51820
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    restart: unless-stopped
    sysctls:
      - net.ipv4.conf.all.src_valid_mark="1"
      - net.ipv4.ip_forward="1"
    volumes:
      - ./wireguard:/etc/wireguard
